updates:
  - directory: /
    package-ecosystem: gradle
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
  - directory: /java-client/
    package-ecosystem: gradle
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
  - directory: /
    package-ecosystem: github-actions
    open-pull-requests-limit: 3
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
      - "github-actions"
version: 2
