version: '3'

services:

  opensearch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SECURE_INTEGRATION=${SECURE_INTEGRATION:-true}
        - OPENSEARCH_VERSION=${OPENSEARCH_VERSION}
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"
    user: opensearch
