name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run Unit Test
        run: ./gradlew clean unitTest

      - name: Run Docker
        run: |
          docker build -t opensearch-search:test -f .ci/opensearch/Dockerfile --build-arg "SECURE_INTEGRATION=true" .
          docker run -p 9200:9200 -p 9600:9600 -d -e "discovery.type=single-node" opensearch-search:test
          sleep 60

      - name: Run Integration Test
        run: ./gradlew clean integrationTest

      - name: Build with Gradle
        run: ./gradlew clean build -x test
