name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: 'opensearch-project/OpenSearch'
          path: OpenSearch
          ref: '1.0.0'
      - name: Build OpenSearch
        working-directory: ./OpenSearch
        run: ./gradlew publishToMavenLocal
      - name: Run Docker
        run: |
          echo "FROM opensearchproject/opensearch:1.0.0" >> Dockerfile
          echo "RUN /usr/share/opensearch/bin/opensearch-plugin remove opensearch-security" >> Dockerfile
          echo "RUN rm /usr/share/opensearch/config/opensearch.yml" >> Dockerfile
          echo "RUN echo 'cluster.name: \"docker-cluster\"' >> /usr/share/opensearch/config/opensearch.yml" >> Dockerfile
          echo "RUN echo 'network.host: 0.0.0.0' >> /usr/share/opensearch/config/opensearch.yml" >> Dockerfile
          echo "RUN cat /usr/share/opensearch/config/opensearch.yml" >> Dockerfile
          docker build -t opensearch-search:test .
          docker run -p 9200:9200 -p 9600:9600 -d -e "discovery.type=single-node" opensearch-search:test
          sleep 90
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build
