name: Code style and license headers

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 11 ]
    steps:
      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
      - uses: actions/checkout@v2
      - name: Check style and license headers
        run: |
          ./gradlew checkstyleMain checkstyleTest
