name: Integration with Unreleased OpenSearch

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { opensearch_ref: '1.x', java: 11 }
          - { opensearch_ref: '2.x', java: 11 }
          - { opensearch_ref: '2.x', java: 17 }
          - { opensearch_ref: '2.0', java: 11 }
          - { opensearch_ref: 'main', java: 11 }
          - { opensearch_ref: 'main', java: 17 }
    steps:
      - name: Set up JDK ${{ matrix.entry.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.entry.java }}

      - name: Checkout OpenSearch
        uses: actions/checkout@v2
        with:
          repository: opensearch-project/OpenSearch
          ref: ${{ matrix.entry.opensearch_ref }}
          path: opensearch

      - name: Assemble OpenSearch
        run: |
          cd opensearch
          ./gradlew assemble

        # This step runs the docker image generated during gradle assemble in OpenSearch. It is tagged as opensearch:test.
        # Reference: https://github.com/opensearch-project/OpenSearch/blob/2.0/distribution/docker/build.gradle#L190
      - name: Run Docker Image
        run: |
          docker run -p 9200:9200 -p 9600:9600 -d -e "discovery.type=single-node" -e "bootstrap.memory_lock=true" opensearch:test
          sleep 90

      - name: Checkout Java Client
        uses: actions/checkout@v2
        with:
          path: opensearch-java

      - name: Run Integration Test
        run: |
          cd opensearch-java
          ./gradlew clean integrationTest -Dhttps=false

      - name: Upload Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: opensearch-java/java-client/build/reports/
          retention-days: 7
