name: Unit

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 11, 17, 21 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout Java Client
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Unit Test
        run: ./gradlew clean unitTest
  
  test-java8:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-13]
    steps:
      - name: Checkout Java Client
        uses: actions/checkout@v3

      - name: Set up JDK 8 (Runtime)
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: temurin
          cache: gradle

      - name: Set up JDK 11 (Tools)
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle

      - name: Run Unit Test
        run: ./gradlew clean unitTest -D"runtime.java=8"
