name: Integration with Released OpenSearch

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { opensearch_version: 1.0.1, java: 11 }
          - { opensearch_version: 1.1.0, java: 11 }
          - { opensearch_version: 1.2.4, java: 11 }
          - { opensearch_version: 1.3.5, java: 11 }
          - { opensearch_version: 2.0.1, java: 11 }
          - { opensearch_version: 2.1.0, java: 11 }
          - { opensearch_version: 2.2.1, java: 11 }
          - { opensearch_version: 2.3.0, java: 11 }
    steps:
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.entry.java }}

      - name: Checkout Branch
        uses: actions/checkout@v2

      - name: Run Docker
        run: |
          docker-compose --project-directory .ci/opensearch build --build-arg OPENSEARCH_VERSION=${{ matrix.entry.opensearch_version }}
          docker-compose --project-directory .ci/opensearch up -d
          sleep 60
      - name: Run Integration Test
        run: ./gradlew clean integrationTest

      - name: Stop Docker
        run: |
          docker-compose --project-directory .ci/opensearch down